# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, unique=True)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=22)),
                ('account', models.CharField(max_length=20)),
                ('os', models.CharField(choices=[('C', 'Centos'), ('R', 'Redhat'), ('U', 'Ubuntu'), ('B', 'Bsd'), ('D', 'Debian')], max_length=4)),
                ('activate', models.BooleanField(default=True)),
            ],
        ),
    ]
