# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='password',
            field=models.CharField(default=123456, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='os',
            field=models.CharField(choices=[('C', 'Centos'), ('R', 'Redhat'), ('U', 'Ubuntu'), ('B', 'Bsd'), ('D', 'Debian')], default='C', max_length=4),
        ),
    ]
