# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('user_number', models.IntegerField(max_length=20)),
                ('host_number', models.IntegerField(max_length=20)),
                ('remark', models.CharField(max_length=128)),
            ],
        ),
    ]
