# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-15 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190914_0147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='asserts',
            field=models.ManyToManyField(to='assets.Assets'),
        ),
        migrations.AddField(
            model_name='perm',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perm',
            name='host_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='perm',
            name='user_number',
            field=models.IntegerField(),
        ),
    ]
