# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_auto_20190915_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perm',
            name='host_number',
        ),
        migrations.RemoveField(
            model_name='perm',
            name='user_number',
        ),
        migrations.AddField(
            model_name='perm',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perm',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
