# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-23 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0003_auto_20190915_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perm',
            old_name='asserts',
            new_name='assets',
        ),
    ]
